START TRANSACTION;

CREATE TABLE "Characters" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Description" text NULL,
    "Name" character varying(100) NOT NULL,
    "Player" character varying(100) NULL,
    "WorldId" integer NOT NULL,
    "Stature" double precision NOT NULL DEFAULT 0.0,
    "Weight" double precision NOT NULL DEFAULT 0.0,
    "Age" integer NOT NULL DEFAULT 0,
    "Experience" integer NOT NULL DEFAULT 0,
    "Vitality" integer NOT NULL DEFAULT 0,
    "Stamina" integer NOT NULL DEFAULT 0,
    "BloodAlcoholContent" integer NOT NULL DEFAULT 0,
    "Intoxication" integer NOT NULL DEFAULT 0,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (now()),
    "CreatedById" uuid NOT NULL,
    "Deleted" boolean NOT NULL DEFAULT FALSE,
    "DeletedAt" timestamp with time zone NULL,
    "DeletedById" uuid NULL,
    "Key" uuid NOT NULL DEFAULT (uuid_generate_v4()),
    "UpdatedAt" timestamp with time zone NULL,
    "UpdatedById" uuid NULL,
    "Version" integer NOT NULL DEFAULT 0,
    CONSTRAINT "PK_Characters" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Characters_Worlds_WorldId" FOREIGN KEY ("WorldId") REFERENCES "Worlds" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Characters_CreatedById" ON "Characters" ("CreatedById");

CREATE INDEX "IX_Characters_Deleted" ON "Characters" ("Deleted");

CREATE UNIQUE INDEX "IX_Characters_Key" ON "Characters" ("Key");

CREATE INDEX "IX_Characters_Name" ON "Characters" ("Name");

CREATE INDEX "IX_Characters_WorldId" ON "Characters" ("WorldId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20220406130047_CreateCharacterTable', '6.0.3');

COMMIT;
