START TRANSACTION;

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE "EventLogs" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(256) NOT NULL,
    "Method" character varying(16) NULL,
    "Url" character varying(2048) NULL,
    "Data" text NULL,
    "StatusCode" integer NULL,
    "StartedAt" timestamp with time zone NOT NULL DEFAULT (now()),
    "EndedAt" timestamp with time zone NULL,
    "RequestTime" interval NULL,
    "IsCompleted" boolean NOT NULL DEFAULT FALSE,
    "Level" integer NOT NULL DEFAULT 0,
    "HasErrors" boolean NOT NULL DEFAULT FALSE,
    "Errors" jsonb NULL,
    "WorldId" uuid NULL,
    "EntityId" uuid NULL,
    "EntityType" character varying(256) NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (now()),
    "CreatedById" uuid NOT NULL,
    "Deleted" boolean NOT NULL DEFAULT FALSE,
    "DeletedAt" timestamp with time zone NULL,
    "DeletedById" uuid NULL,
    "UpdatedAt" timestamp with time zone NULL,
    "UpdatedById" uuid NULL,
    "Uuid" uuid NOT NULL DEFAULT (uuid_generate_v4()),
    "Version" integer NOT NULL DEFAULT 0,
    CONSTRAINT "PK_EventLogs" PRIMARY KEY ("Id")
);

CREATE TABLE "Worlds" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Alias" character varying(256) NOT NULL,
    "Description" text NULL,
    "Name" character varying(256) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (now()),
    "CreatedById" uuid NOT NULL,
    "Deleted" boolean NOT NULL DEFAULT FALSE,
    "DeletedAt" timestamp with time zone NULL,
    "DeletedById" uuid NULL,
    "UpdatedAt" timestamp with time zone NULL,
    "UpdatedById" uuid NULL,
    "Uuid" uuid NOT NULL DEFAULT (uuid_generate_v4()),
    "Version" integer NOT NULL DEFAULT 0,
    CONSTRAINT "PK_Worlds" PRIMARY KEY ("Id")
);

CREATE INDEX "IX_EventLogs_CreatedById" ON "EventLogs" ("CreatedById");

CREATE INDEX "IX_EventLogs_Deleted" ON "EventLogs" ("Deleted");

CREATE UNIQUE INDEX "IX_EventLogs_Uuid" ON "EventLogs" ("Uuid");

CREATE UNIQUE INDEX "IX_Worlds_Alias" ON "Worlds" ("Alias");

CREATE INDEX "IX_Worlds_CreatedById" ON "Worlds" ("CreatedById");

CREATE INDEX "IX_Worlds_Deleted" ON "Worlds" ("Deleted");

CREATE INDEX "IX_Worlds_Name" ON "Worlds" ("Name");

CREATE UNIQUE INDEX "IX_Worlds_Uuid" ON "Worlds" ("Uuid");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20220609045913_CreateEventLogAndWorldTables', '6.0.5');

COMMIT;
