START TRANSACTION;

CREATE TABLE "Races" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "WorldId" integer NOT NULL,
    "Description" text NULL,
    "Name" character varying(256) NOT NULL,
    "Attributes" character varying(100) NULL,
    "Names" jsonb NULL,
    "Speeds" character varying(50) NULL,
    "AgeThresholds" integer[] NULL,
    "Size" integer NOT NULL,
    "StatureRoll" character varying(10) NULL,
    "WeightRolls" character varying(10)[] NULL,
    "Traits" jsonb NULL,
    "ExtraAttributes" integer NOT NULL,
    "ExtraLanguages" integer NOT NULL,
    "AgeText" text NULL,
    "AttributesText" text NULL,
    "LanguagesText" text NULL,
    "NamesText" text NULL,
    "SizeText" text NULL,
    "SpeedText" text NULL,
    "SubraceText" text NULL,
    "TraitsText" text NULL,
    "WeightText" text NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (now()),
    "CreatedById" uuid NOT NULL,
    "Deleted" boolean NOT NULL DEFAULT FALSE,
    "DeletedAt" timestamp with time zone NULL,
    "DeletedById" uuid NULL,
    "UpdatedAt" timestamp with time zone NULL,
    "UpdatedById" uuid NULL,
    "Uuid" uuid NOT NULL DEFAULT (uuid_generate_v4()),
    "Version" integer NOT NULL DEFAULT 0,
    CONSTRAINT "PK_Races" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Races_Worlds_WorldId" FOREIGN KEY ("WorldId") REFERENCES "Worlds" ("Id") ON DELETE CASCADE
);

CREATE TABLE "RaceLanguages" (
    "RaceId" integer NOT NULL,
    "LanguageId" integer NOT NULL,
    CONSTRAINT "PK_RaceLanguages" PRIMARY KEY ("RaceId", "LanguageId"),
    CONSTRAINT "FK_RaceLanguages_Languages_LanguageId" FOREIGN KEY ("LanguageId") REFERENCES "Languages" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_RaceLanguages_Races_RaceId" FOREIGN KEY ("RaceId") REFERENCES "Races" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_RaceLanguages_LanguageId" ON "RaceLanguages" ("LanguageId");

CREATE INDEX "IX_Races_CreatedById" ON "Races" ("CreatedById");

CREATE INDEX "IX_Races_Deleted" ON "Races" ("Deleted");

CREATE INDEX "IX_Races_Name" ON "Races" ("Name");

CREATE UNIQUE INDEX "IX_Races_Uuid" ON "Races" ("Uuid");

CREATE INDEX "IX_Races_WorldId" ON "Races" ("WorldId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20220617014831_CreateRaceTables', '6.0.5');

COMMIT;
