START TRANSACTION;

CREATE TABLE "Castes" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Description" text NULL,
    "Name" character varying(100) NOT NULL,
    "Skill" integer NULL,
    "WealthRoll" character varying(10) NULL,
    "WorldId" integer NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (now()),
    "CreatedById" uuid NOT NULL,
    "Deleted" boolean NOT NULL DEFAULT FALSE,
    "DeletedAt" timestamp with time zone NULL,
    "DeletedById" uuid NULL,
    "Key" uuid NOT NULL DEFAULT (uuid_generate_v4()),
    "UpdatedAt" timestamp with time zone NULL,
    "UpdatedById" uuid NULL,
    "Version" integer NOT NULL DEFAULT 0,
    CONSTRAINT "PK_Castes" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Castes_Worlds_WorldId" FOREIGN KEY ("WorldId") REFERENCES "Worlds" ("Id")
);

CREATE TABLE "CasteTraits" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CasteId" integer NOT NULL,
    "Description" text NULL,
    "Key" uuid NOT NULL DEFAULT (uuid_generate_v4()),
    "Name" character varying(100) NOT NULL,
    CONSTRAINT "PK_CasteTraits" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_CasteTraits_Castes_CasteId" FOREIGN KEY ("CasteId") REFERENCES "Castes" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Castes_CreatedById" ON "Castes" ("CreatedById");

CREATE INDEX "IX_Castes_Deleted" ON "Castes" ("Deleted");

CREATE UNIQUE INDEX "IX_Castes_Key" ON "Castes" ("Key");

CREATE INDEX "IX_Castes_Name" ON "Castes" ("Name");

CREATE INDEX "IX_Castes_WorldId" ON "Castes" ("WorldId");

CREATE INDEX "IX_CasteTraits_CasteId" ON "CasteTraits" ("CasteId");

CREATE UNIQUE INDEX "IX_CasteTraits_Key" ON "CasteTraits" ("Key");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20220405134651_CreateCasteTables', '6.0.3');

COMMIT;
