START TRANSACTION;

CREATE TABLE "Characters" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "WorldId" integer NOT NULL,
    "Name" character varying(100) NULL,
    "Player" character varying(100) NULL,
    "Aspect1Id" integer NULL,
    "Aspect2Id" integer NULL,
    "RaceId" integer NULL,
    "NatureId" integer NULL,
    "CasteId" integer NULL,
    "EducationId" integer NULL,
    "Size" integer NOT NULL DEFAULT 0,
    "Stature" double precision NOT NULL DEFAULT 0.0,
    "Weight" double precision NOT NULL DEFAULT 0.0,
    "Age" integer NOT NULL DEFAULT 0,
    "Experience" integer NOT NULL DEFAULT 0,
    "Vitality" integer NOT NULL DEFAULT 0,
    "Stamina" integer NOT NULL DEFAULT 0,
    "BloodAlcoholContent" integer NOT NULL DEFAULT 0,
    "Intoxication" integer NOT NULL DEFAULT 0,
    "Description" text NULL,
    "Creation" jsonb NULL,
    "LevelUps" jsonb NULL,
    "SkillRanks" jsonb NULL,
    "Bonuses" jsonb[] NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (now()),
    "CreatedById" uuid NOT NULL,
    "Deleted" boolean NOT NULL DEFAULT FALSE,
    "DeletedAt" timestamp with time zone NULL,
    "DeletedById" uuid NULL,
    "UpdatedAt" timestamp with time zone NULL,
    "UpdatedById" uuid NULL,
    "Uuid" uuid NOT NULL DEFAULT (uuid_generate_v4()),
    "Version" integer NOT NULL DEFAULT 0,
    CONSTRAINT "PK_Characters" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Characters_Aspects_Aspect1Id" FOREIGN KEY ("Aspect1Id") REFERENCES "Aspects" ("Id"),
    CONSTRAINT "FK_Characters_Aspects_Aspect2Id" FOREIGN KEY ("Aspect2Id") REFERENCES "Aspects" ("Id"),
    CONSTRAINT "FK_Characters_Castes_CasteId" FOREIGN KEY ("CasteId") REFERENCES "Castes" ("Id"),
    CONSTRAINT "FK_Characters_Educations_EducationId" FOREIGN KEY ("EducationId") REFERENCES "Educations" ("Id"),
    CONSTRAINT "FK_Characters_Natures_NatureId" FOREIGN KEY ("NatureId") REFERENCES "Natures" ("Id"),
    CONSTRAINT "FK_Characters_Races_RaceId" FOREIGN KEY ("RaceId") REFERENCES "Races" ("Id"),
    CONSTRAINT "FK_Characters_Worlds_WorldId" FOREIGN KEY ("WorldId") REFERENCES "Worlds" ("Id") ON DELETE CASCADE
);

CREATE TABLE "CharacterCondition" (
    "CharacterId" integer NOT NULL,
    "ConditionId" integer NOT NULL,
    "Level" integer NOT NULL,
    CONSTRAINT "PK_CharacterCondition" PRIMARY KEY ("CharacterId", "ConditionId"),
    CONSTRAINT "FK_CharacterCondition_Characters_CharacterId" FOREIGN KEY ("CharacterId") REFERENCES "Characters" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_CharacterCondition_Conditions_ConditionId" FOREIGN KEY ("ConditionId") REFERENCES "Conditions" ("Id") ON DELETE CASCADE
);

CREATE TABLE "CharacterLanguages" (
    "CharacterId" integer NOT NULL,
    "LanguageId" integer NOT NULL,
    CONSTRAINT "PK_CharacterLanguages" PRIMARY KEY ("CharacterId", "LanguageId"),
    CONSTRAINT "FK_CharacterLanguages_Characters_CharacterId" FOREIGN KEY ("CharacterId") REFERENCES "Characters" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_CharacterLanguages_Languages_LanguageId" FOREIGN KEY ("LanguageId") REFERENCES "Languages" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_CharacterCondition_ConditionId" ON "CharacterCondition" ("ConditionId");

CREATE INDEX "IX_CharacterLanguages_LanguageId" ON "CharacterLanguages" ("LanguageId");

CREATE INDEX "IX_Characters_Aspect1Id" ON "Characters" ("Aspect1Id");

CREATE INDEX "IX_Characters_Aspect2Id" ON "Characters" ("Aspect2Id");

CREATE INDEX "IX_Characters_CasteId" ON "Characters" ("CasteId");

CREATE INDEX "IX_Characters_CreatedById" ON "Characters" ("CreatedById");

CREATE INDEX "IX_Characters_Deleted" ON "Characters" ("Deleted");

CREATE INDEX "IX_Characters_EducationId" ON "Characters" ("EducationId");

CREATE INDEX "IX_Characters_Name" ON "Characters" ("Name");

CREATE INDEX "IX_Characters_NatureId" ON "Characters" ("NatureId");

CREATE INDEX "IX_Characters_Player" ON "Characters" ("Player");

CREATE INDEX "IX_Characters_RaceId" ON "Characters" ("RaceId");

CREATE UNIQUE INDEX "IX_Characters_Uuid" ON "Characters" ("Uuid");

CREATE INDEX "IX_Characters_WorldId" ON "Characters" ("WorldId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20220620201254_CreateCharacterTable', '6.0.5');

COMMIT;
