START TRANSACTION;

CREATE TABLE "Worlds" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Alias" character varying(100) NOT NULL,
    "Confidentiality" integer NOT NULL DEFAULT 0,
    "Description" text NULL,
    "Name" character varying(100) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (now()),
    "CreatedById" uuid NOT NULL,
    "Deleted" boolean NOT NULL DEFAULT FALSE,
    "DeletedAt" timestamp with time zone NULL,
    "DeletedById" uuid NULL,
    "Key" uuid NOT NULL DEFAULT (uuid_generate_v4()),
    "UpdatedAt" timestamp with time zone NULL,
    "UpdatedById" uuid NULL,
    "Version" integer NOT NULL DEFAULT 0,
    CONSTRAINT "PK_Worlds" PRIMARY KEY ("Id")
);

CREATE TABLE "Aspects" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Description" text NULL,
    "Name" character varying(100) NOT NULL,
    "WorldId" integer NOT NULL,
    "MandatoryAttribute1" integer NULL,
    "MandatoryAttribute2" integer NULL,
    "OptionalAttribute1" integer NULL,
    "OptionalAttribute2" integer NULL,
    "Skill1" integer NULL,
    "Skill2" integer NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (now()),
    "CreatedById" uuid NOT NULL,
    "Deleted" boolean NOT NULL DEFAULT FALSE,
    "DeletedAt" timestamp with time zone NULL,
    "DeletedById" uuid NULL,
    "Key" uuid NOT NULL DEFAULT (uuid_generate_v4()),
    "UpdatedAt" timestamp with time zone NULL,
    "UpdatedById" uuid NULL,
    "Version" integer NOT NULL DEFAULT 0,
    CONSTRAINT "PK_Aspects" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Aspects_Worlds_WorldId" FOREIGN KEY ("WorldId") REFERENCES "Worlds" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Disabilities" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Description" text NULL,
    "Name" character varying(100) NOT NULL,
    "WorldId" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (now()),
    "CreatedById" uuid NOT NULL,
    "Deleted" boolean NOT NULL DEFAULT FALSE,
    "DeletedAt" timestamp with time zone NULL,
    "DeletedById" uuid NULL,
    "Key" uuid NOT NULL DEFAULT (uuid_generate_v4()),
    "UpdatedAt" timestamp with time zone NULL,
    "UpdatedById" uuid NULL,
    "Version" integer NOT NULL DEFAULT 0,
    CONSTRAINT "PK_Disabilities" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Disabilities_Worlds_WorldId" FOREIGN KEY ("WorldId") REFERENCES "Worlds" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Gifts" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Description" text NULL,
    "Name" character varying(100) NOT NULL,
    "WorldId" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (now()),
    "CreatedById" uuid NOT NULL,
    "Deleted" boolean NOT NULL DEFAULT FALSE,
    "DeletedAt" timestamp with time zone NULL,
    "DeletedById" uuid NULL,
    "Key" uuid NOT NULL DEFAULT (uuid_generate_v4()),
    "UpdatedAt" timestamp with time zone NULL,
    "UpdatedById" uuid NULL,
    "Version" integer NOT NULL DEFAULT 0,
    CONSTRAINT "PK_Gifts" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Gifts_Worlds_WorldId" FOREIGN KEY ("WorldId") REFERENCES "Worlds" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Natures" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Attribute" integer NULL,
    "Description" text NULL,
    "GiftId" integer NULL,
    "Name" character varying(100) NOT NULL,
    "WorldId" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (now()),
    "CreatedById" uuid NOT NULL,
    "Deleted" boolean NOT NULL DEFAULT FALSE,
    "DeletedAt" timestamp with time zone NULL,
    "DeletedById" uuid NULL,
    "Key" uuid NOT NULL DEFAULT (uuid_generate_v4()),
    "UpdatedAt" timestamp with time zone NULL,
    "UpdatedById" uuid NULL,
    "Version" integer NOT NULL DEFAULT 0,
    CONSTRAINT "PK_Natures" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Natures_Gifts_GiftId" FOREIGN KEY ("GiftId") REFERENCES "Gifts" ("Id"),
    CONSTRAINT "FK_Natures_Worlds_WorldId" FOREIGN KEY ("WorldId") REFERENCES "Worlds" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Aspects_CreatedById" ON "Aspects" ("CreatedById");

CREATE INDEX "IX_Aspects_Deleted" ON "Aspects" ("Deleted");

CREATE UNIQUE INDEX "IX_Aspects_Key" ON "Aspects" ("Key");

CREATE INDEX "IX_Aspects_Name" ON "Aspects" ("Name");

CREATE INDEX "IX_Aspects_WorldId" ON "Aspects" ("WorldId");

CREATE INDEX "IX_Disabilities_CreatedById" ON "Disabilities" ("CreatedById");

CREATE INDEX "IX_Disabilities_Deleted" ON "Disabilities" ("Deleted");

CREATE UNIQUE INDEX "IX_Disabilities_Key" ON "Disabilities" ("Key");

CREATE INDEX "IX_Disabilities_Name" ON "Disabilities" ("Name");

CREATE INDEX "IX_Disabilities_WorldId" ON "Disabilities" ("WorldId");

CREATE INDEX "IX_Gifts_CreatedById" ON "Gifts" ("CreatedById");

CREATE INDEX "IX_Gifts_Deleted" ON "Gifts" ("Deleted");

CREATE UNIQUE INDEX "IX_Gifts_Key" ON "Gifts" ("Key");

CREATE INDEX "IX_Gifts_Name" ON "Gifts" ("Name");

CREATE INDEX "IX_Gifts_WorldId" ON "Gifts" ("WorldId");

CREATE INDEX "IX_Natures_CreatedById" ON "Natures" ("CreatedById");

CREATE INDEX "IX_Natures_Deleted" ON "Natures" ("Deleted");

CREATE INDEX "IX_Natures_GiftId" ON "Natures" ("GiftId");

CREATE UNIQUE INDEX "IX_Natures_Key" ON "Natures" ("Key");

CREATE INDEX "IX_Natures_Name" ON "Natures" ("Name");

CREATE INDEX "IX_Natures_WorldId" ON "Natures" ("WorldId");

CREATE UNIQUE INDEX "IX_Worlds_Alias" ON "Worlds" ("Alias");

CREATE INDEX "IX_Worlds_CreatedById" ON "Worlds" ("CreatedById");

CREATE INDEX "IX_Worlds_Deleted" ON "Worlds" ("Deleted");

CREATE UNIQUE INDEX "IX_Worlds_Key" ON "Worlds" ("Key");

CREATE INDEX "IX_Worlds_Name" ON "Worlds" ("Name");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20220404231432_CreatedBaseTables', '6.0.3');

COMMIT;
