START TRANSACTION;

CREATE TABLE "Aspects" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "WorldId" integer NOT NULL,
    "Description" text NULL,
    "Name" character varying(256) NOT NULL,
    "MandatoryAttribute1" integer NOT NULL,
    "MandatoryAttribute2" integer NOT NULL,
    "OptionalAttribute1" integer NOT NULL,
    "OptionalAttribute2" integer NOT NULL,
    "Skill1" integer NOT NULL,
    "Skill2" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (now()),
    "CreatedById" uuid NOT NULL,
    "Deleted" boolean NOT NULL DEFAULT FALSE,
    "DeletedAt" timestamp with time zone NULL,
    "DeletedById" uuid NULL,
    "UpdatedAt" timestamp with time zone NULL,
    "UpdatedById" uuid NULL,
    "Uuid" uuid NOT NULL DEFAULT (uuid_generate_v4()),
    "Version" integer NOT NULL DEFAULT 0,
    CONSTRAINT "PK_Aspects" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Aspects_Worlds_WorldId" FOREIGN KEY ("WorldId") REFERENCES "Worlds" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Aspects_CreatedById" ON "Aspects" ("CreatedById");

CREATE INDEX "IX_Aspects_Deleted" ON "Aspects" ("Deleted");

CREATE INDEX "IX_Aspects_Name" ON "Aspects" ("Name");

CREATE UNIQUE INDEX "IX_Aspects_Uuid" ON "Aspects" ("Uuid");

CREATE INDEX "IX_Aspects_WorldId" ON "Aspects" ("WorldId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20220609163910_CreateAspectTable', '6.0.5');

COMMIT;
