START TRANSACTION;

CREATE TABLE "Talents" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "WorldId" integer NOT NULL,
    "MultipleAcquisition" boolean NOT NULL DEFAULT FALSE,
    "RequiredTalentId" integer NULL,
    "Skill" integer NULL,
    "Tier" integer NOT NULL,
    "Name" character varying(256) NOT NULL,
    "Description" text NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (now()),
    "CreatedById" uuid NOT NULL,
    "Deleted" boolean NOT NULL DEFAULT FALSE,
    "DeletedAt" timestamp with time zone NULL,
    "DeletedById" uuid NULL,
    "UpdatedAt" timestamp with time zone NULL,
    "UpdatedById" uuid NULL,
    "Uuid" uuid NOT NULL DEFAULT (uuid_generate_v4()),
    "Version" integer NOT NULL DEFAULT 0,
    CONSTRAINT "PK_Talents" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Talents_Talents_RequiredTalentId" FOREIGN KEY ("RequiredTalentId") REFERENCES "Talents" ("Id"),
    CONSTRAINT "FK_Talents_Worlds_WorldId" FOREIGN KEY ("WorldId") REFERENCES "Worlds" ("Id") ON DELETE CASCADE
);

CREATE TABLE "TalentOptions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Uuid" uuid NOT NULL DEFAULT (uuid_generate_v4()),
    "TalentId" integer NOT NULL,
    "Name" character varying(128) NOT NULL,
    "Description" text NULL,
    CONSTRAINT "PK_TalentOptions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TalentOptions_Talents_TalentId" FOREIGN KEY ("TalentId") REFERENCES "Talents" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_TalentOptions_TalentId" ON "TalentOptions" ("TalentId");

CREATE UNIQUE INDEX "IX_TalentOptions_Uuid" ON "TalentOptions" ("Uuid");

CREATE INDEX "IX_Talents_CreatedById" ON "Talents" ("CreatedById");

CREATE INDEX "IX_Talents_Deleted" ON "Talents" ("Deleted");

CREATE INDEX "IX_Talents_MultipleAcquisition" ON "Talents" ("MultipleAcquisition");

CREATE INDEX "IX_Talents_Name" ON "Talents" ("Name");

CREATE INDEX "IX_Talents_RequiredTalentId" ON "Talents" ("RequiredTalentId");

CREATE INDEX "IX_Talents_Tier" ON "Talents" ("Tier");

CREATE UNIQUE INDEX "IX_Talents_Uuid" ON "Talents" ("Uuid");

CREATE INDEX "IX_Talents_WorldId" ON "Talents" ("WorldId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20220622044914_CreateTalentTables', '6.0.5');

COMMIT;
