START TRANSACTION;

CREATE TABLE "Worlds" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Alias" character varying(100) NOT NULL,
    "Confidentiality" integer NOT NULL,
    "Description" text NULL,
    "Name" character varying(100) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (now()),
    "CreatedById" uuid NOT NULL,
    "Deleted" boolean NOT NULL DEFAULT FALSE,
    "DeletedAt" timestamp with time zone NULL,
    "DeletedById" uuid NULL,
    "Key" uuid NOT NULL DEFAULT (uuid_generate_v4()),
    "UpdatedAt" timestamp with time zone NULL,
    "UpdatedById" uuid NULL,
    "Version" integer NOT NULL DEFAULT 0,
    CONSTRAINT "PK_Worlds" PRIMARY KEY ("Id")
);

CREATE UNIQUE INDEX "IX_Worlds_Alias" ON "Worlds" ("Alias");

CREATE INDEX "IX_Worlds_CreatedById" ON "Worlds" ("CreatedById");

CREATE INDEX "IX_Worlds_Deleted" ON "Worlds" ("Deleted");

CREATE UNIQUE INDEX "IX_Worlds_Key" ON "Worlds" ("Key");

CREATE INDEX "IX_Worlds_Name" ON "Worlds" ("Name");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20220330195915_CreateWorldTable', '6.0.3');

COMMIT;
