START TRANSACTION;

CREATE TABLE "Powers" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "WorldId" integer NOT NULL,
    "Tier" integer NOT NULL,
    "Name" character varying(256) NOT NULL,
    "Descriptions" text[] NULL,
    "Incantation" integer NOT NULL DEFAULT 0,
    "Duration" integer NULL,
    "Range" integer NULL,
    "Ingredients" text NULL,
    "Concentration" boolean NOT NULL DEFAULT FALSE,
    "Focus" boolean NOT NULL DEFAULT FALSE,
    "Ritual" boolean NOT NULL DEFAULT FALSE,
    "Somatic" boolean NOT NULL DEFAULT FALSE,
    "Verbal" boolean NOT NULL DEFAULT FALSE,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (now()),
    "CreatedById" uuid NOT NULL,
    "Deleted" boolean NOT NULL DEFAULT FALSE,
    "DeletedAt" timestamp with time zone NULL,
    "DeletedById" uuid NULL,
    "UpdatedAt" timestamp with time zone NULL,
    "UpdatedById" uuid NULL,
    "Uuid" uuid NOT NULL DEFAULT (uuid_generate_v4()),
    "Version" integer NOT NULL DEFAULT 0,
    CONSTRAINT "PK_Powers" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Powers_Worlds_WorldId" FOREIGN KEY ("WorldId") REFERENCES "Worlds" ("Id") ON DELETE CASCADE
);

CREATE TABLE "CharacterPowers" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Uuid" uuid NOT NULL DEFAULT (uuid_generate_v4()),
    "CharacterId" integer NOT NULL,
    "PowerId" integer NOT NULL,
    "Cost" integer NOT NULL DEFAULT 0,
    "Description" text NULL,
    CONSTRAINT "PK_CharacterPowers" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_CharacterPowers_Characters_CharacterId" FOREIGN KEY ("CharacterId") REFERENCES "Characters" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_CharacterPowers_Powers_PowerId" FOREIGN KEY ("PowerId") REFERENCES "Powers" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_CharacterPowers_CharacterId" ON "CharacterPowers" ("CharacterId");

CREATE INDEX "IX_CharacterPowers_PowerId" ON "CharacterPowers" ("PowerId");

CREATE UNIQUE INDEX "IX_CharacterPowers_Uuid" ON "CharacterPowers" ("Uuid");

CREATE INDEX "IX_Powers_CreatedById" ON "Powers" ("CreatedById");

CREATE INDEX "IX_Powers_Deleted" ON "Powers" ("Deleted");

CREATE INDEX "IX_Powers_Name" ON "Powers" ("Name");

CREATE INDEX "IX_Powers_Tier" ON "Powers" ("Tier");

CREATE UNIQUE INDEX "IX_Powers_Uuid" ON "Powers" ("Uuid");

CREATE INDEX "IX_Powers_WorldId" ON "Powers" ("WorldId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20220627025953_CreatePowerTables', '6.0.5');

COMMIT;
