name: Build Development SkillCraft

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: docker build . -t francispion.azurecr.io/skillcraft:${{ github.sha }} -f src/SkillCraft/Dockerfile
